[server]
    debug = true
    needDoc=true
    docName="天气"
    docDesc="Weather"
    port=5858
    openDocInBrowser=false
    docDomain=""
    docVer="v1"
    redirectToDocWhenAccessRoot=true
    apiBasePath="/"
    staticDir=""
    [server.cors]
        allowHeaders = ["Origin","Content-Length","Content-Type","Authorization","x-requested-with"]