[server]
    debug = true
    needDoc=true
    docName="KAPI Example"
    docDesc="Example Api"
    port=3939
    openDocInBrowser=false
    docDomain=""
    docVer="v2"
    redirectToDocWhenAccessRoot=true
    apiBasePath="/"
    staticDir=""
    [server.cors]
        allowHeaders = ["Origin","Content-Length","Content-Type","Authorization","x-requested-with"]