
[server]
debug = false
needDoc = true
needReDoc = false
needSwagger = true
docName = "K-Api"
docDesc = "K-Api"
port = 2022
openDocInBrowser = true
docDomain = ""
docVer = "v1"
redirectToDocWhenAccessRoot = true
apiBasePath = ""
staticDirs = ["static"]
enablePProf = false
[server.cors]
allowHeaders = ["Origin","Content-Length","Content-Type"]
allowAllOrigins = true
