
[server]
debug = true
needDoc = true
docName = "K-Api"
docDesc = "K-Api"
port = 2022
docDomain = ""
docVer = "v1"
redirectToDocWhenAccessRoot = true
staticDirs = ["static"]
enablePProf = true
[server.cors]
allowHeaders = ["Origin","Content-Length","Content-Type"]
#allowAllOrigins = true
